import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import wilayasRouter from "./wilayas";
import categoriesRouter from "./categories";
import servicesRouter from "./services";
import ordersRouter from "./orders";
import reviewsRouter from "./reviews";
import walletRouter from "./wallet";
import disputesRouter from "./disputes";
import notificationsRouter from "./notifications";
import wishlistRouter from "./wishlist";
import statsRouter from "./stats";
import adminRouter from "./admin";
import usersRouter from "./users";
import couponsRouter from "./coupons";
import chatRouter from "./chat";
import escrowRouter from "./escrow";
import sellersRouter from "./sellers";
import contractsRouter from "./contracts";
import filesRouter from "./files";
import affiliationsRouter from "./affiliations";
import sellerAnalyticsRouter from "./seller-analytics";
import blogRouter from "./blog";
import bannersRouter from "./banners";
import reportsRouter from "./reports";
import invoicesRouter from "./invoices";
import appointmentsRouter from "./appointments";
import portfolioRouter from "./portfolio";
import webhooksRouter from "./webhooks";
import apiKeysRouter from "./api-keys";
import trustScoreRouter from "./trust-score";
import waitingListRouter from "./waiting-list";
import betaInvitationsRouter from "./beta-invitations";
import onboardingRouter from "./onboarding";
import fraudRouter from "./fraud";
import activityLogsRouter from "./activity-logs";
import wilayaChangeRouter from "./wilaya-change";
import deliveryCertificateRouter from "./delivery-certificate";
import paymentsRouter from "./payments";
import clientRatingsRouter from "./client-ratings";
import chatAiRouter from './chat-ai';
import directMessagesRouter from './direct-messages';
import smartSearchRouter from './smart-search';
import aiDescriptionRouter from './ai-description';
import aiAnalyzeRouter from './ai-analyze';
import productsRouter from "./products";
import searchSellersRouter from './search-sellers';
import warningsRouter from './warnings';
import twoFactorRouter from "./two-factor";
import trendingRequestsRouter from './trending-requests';

const router: IRouter = Router();
router.use(healthRouter);
router.use(authRouter);
router.use(wilayasRouter);
router.use(categoriesRouter);
router.use(servicesRouter);
router.use(ordersRouter);
router.use(reviewsRouter);
router.use(walletRouter);
router.use(disputesRouter);
router.use(notificationsRouter);
router.use(wishlistRouter);
router.use(statsRouter);
router.use(adminRouter);
router.use(usersRouter);
router.use(couponsRouter);
router.use(chatRouter);
router.use(productsRouter);
router.use(escrowRouter);
router.use(sellersRouter);
router.use(contractsRouter);
router.use(filesRouter);
router.use(affiliationsRouter);
router.use(sellerAnalyticsRouter);
router.use(blogRouter);
router.use(bannersRouter);
router.use(reportsRouter);
router.use(invoicesRouter);
router.use(appointmentsRouter);
router.use(portfolioRouter);
router.use(webhooksRouter);
router.use(apiKeysRouter);
router.use(trustScoreRouter);
router.use(waitingListRouter);
router.use(betaInvitationsRouter);
router.use(onboardingRouter);
router.use(fraudRouter);
router.use(activityLogsRouter);
router.use(wilayaChangeRouter);
router.use(deliveryCertificateRouter);
router.use(paymentsRouter);
router.use(clientRatingsRouter);
router.use(chatAiRouter);
router.use(directMessagesRouter);
router.use(smartSearchRouter);
router.use(aiDescriptionRouter);
router.use(aiAnalyzeRouter);
router.use(searchSellersRouter);
router.use(warningsRouter);
router.use(twoFactorRouter);
router.use(trendingRequestsRouter);
export default router;

